### ISSUE TITLE
CSS语法

### ISSUE THREAD

**Issue by Aestus0** [Aestus0/front-end-restart#6]
# CSS规则

规则分为2种：

* at-rule：at规则
* qualified rule：普通css规则

# at规则

## @charset

指定字符编码方式，使用时必须在最前面

## @import

引入另一个css文件

## @media

媒体查询，根据设备类型进行判断

```css
@media print { 
    body { font-size: 10pt }
}
```

## @page

设置页面打印时的表现设置

```css
@page {
  size: 8.5in 11in;
  margin: 10%;

  @top-left {
    content: "Hamlet";
  }
  @top-right {
    content: "Page " counter(page);
  }
}
```

## @counter-style

定义有序列表的表现形式

## @keyframes

定义动画关键帧

## @fontface

定义字体，icon font技术就是根据这个特性实现的

# 普通规则

* 普通规则
    * 选择器
    * 生命列表
        * 属性
        * 值
            * 值的类型
            * 函数

### css variables

```css

:root {
  --main-color: #06c;
  --accent-color: #006;
}
/* The rest of the CSS file */
#foo h1 {
  color: var(--main-color);
}
```

#### 计算型函数

* calc()
* max()
* min()
* clamp()
* toggle()
* attr()
